# Generated by Django 3.2.9 on 2021-11-13 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoría',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCategoría', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('nombre', models.CharField(max_length=255)),
                ('precio', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('identificador', models.CharField(default='random_id', editable=False, max_length=9, primary_key=True, serialize=False)),
                ('img', models.ImageField(null=True, upload_to='productos')),
                ('categoría', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoría', to='samayShop.categoría')),
            ],
        ),
    ]
