# Generated by Django 3.2.9 on 2021-11-13 22:02

from django.db import migrations, models
import samayShop.models


class Migration(migrations.Migration):

    dependencies = [
        ('samayShop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='identificador',
            field=models.CharField(default=samayShop.models.random_id, editable=False, max_length=9, primary_key=True, serialize=False),
        ),
    ]
