# Generated by Django 3.2.9 on 2021-11-22 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samayShop', '0002_alter_producto_identificador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='stock',
        ),
        migrations.AlterField(
            model_name='categoría',
            name='nombreCategoría',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
